### ISSUE TITLE
Logic player count bug (small priority)

### ISSUE THREAD

**Issue by bjw123** [Sit725-Team8/Dixit-Assignment-Group8#9]
![image](https://user-images.githubusercontent.com/22760097/96674471-db9c9080-13a3-11eb-956e-4e7232c67908.png)

When the last player joins the room it says that you are player 0 we are waiting for 4 more players

Probably will be resolved  by not appearing when last player shows up

**Comment by ma2808203259** [comment]
because 4%4 is zero, A if statement will fix this
